"""Generates src/markerImages.ts: the user-marker icons as inline PNG data URIs.

    python3 packages/native-map/scripts/generate-marker-images.py

Fills are SDF images (signed distance fields, tinted at runtime with `icon-color`) so
they follow `userMarkerColor`. The arrow's white disc is drawn by the map as circles.
Needs Pillow.
"""
import base64
import io
import math
import os

from PIL import Image

SCALE = 3  # Images are drawn for 3x screens.
SDF_RADIUS = 8  # MapLibre / tiny-sdf convention: edge at alpha 0.75, 1/8 per pixel.


def seg_dist(px, py, ax, ay, bx, by):
    dx, dy = bx - ax, by - ay
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
    return math.hypot(px - ax - t * dx, py - ay - t * dy)


def inside(px, py, poly):
    result = False
    j = len(poly) - 1
    for i, (xi, yi) in enumerate(poly):
        xj, yj = poly[j]
        if (yi > py) != (yj > py) and px < (xj - xi) * (py - yi) / (yj - yi) + xi:
            result = not result
        j = i
    return result


def signed_distance(px, py, poly):
    d = min(seg_dist(px, py, *poly[i], *poly[(i + 1) % len(poly)]) for i in range(len(poly)))
    return -d if inside(px, py, poly) else d


def render(size, poly, sdf):
    img = Image.new("RGBA", (size, size))
    pixels = img.load()
    for y in range(size):
        for x in range(size):
            d = signed_distance(x + 0.5, y + 0.5, poly)
            if sdf:
                a = 255 - 255 * (d / SDF_RADIUS + 0.25)
            else:
                a = 255 * max(0.0, min(1.0, 0.5 - d))  # 1 px anti-aliased edge
            pixels[x, y] = (255, 255, 255, int(max(0, min(255, round(a)))))
    return img


def data_uri(img):
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


# Navigation arrow, pointing north: 30 dp, centred.
A = 90
arrow = [(45, 10), (76, 78), (45, 62), (14, 78)]
arrow_fill = render(A, arrow, sdf=True)

# Facing cone: a 70° wedge from the centre northwards, 40 dp image.
C = 120
cx = cy = C / 2
r = C / 2 - 4
cone = [(cx, cy)] + [
    (cx + r * math.sin(math.radians(a)), cy - r * math.cos(math.radians(a))) for a in range(-35, 36, 5)
]
cone_fill = render(C, cone, sdf=True)

out = os.path.join(os.path.dirname(__file__), "..", "src", "markerImages.ts")
with open(out, "w") as f:
    f.write("// Generated by scripts/generate-marker-images.py. Do not edit.\n\n")
    for name, img, sdf in [
        ("ARROW_FILL", arrow_fill, True),
        ("CONE_FILL", cone_fill, True),
    ]:
        f.write(f'export const {name} = {{\n  source: {{ uri: "{data_uri(img)}", scale: {SCALE} }},\n  sdf: {str(sdf).lower()},\n}};\n\n')
print("wrote", os.path.normpath(out))
